# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S3MediaTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AWSS3', '~> 2.9.0'
pod 'AWSMobileClient', '~> 2.9.0'

end
